### ISSUE TITLE
Pargraph summary of SSL and letsencrypt

### ISSUE THREAD

**Issue by bulbil** [swat-ds/2018-liblab-projects#1]
- [What is SSL?](https://en.wikipedia.org/wiki/SSL)
- What is [letsencrypt](https://letsencrypt.org/)?

Due Monday 11/12

**Comment by Mualpha7** [comment]
-What is SSL?
SSL, or Secure Sockets Layer, is a cryptographic protocol designed to provide communication security over computer networks. Technically, SSL is the predecessor of TLS (Transport Layer Security), which is the current protocol that is in use, but the name SSL stuck and is used interchangeably with TLS. What SSL does is it makes internet connections secure by protecting, through encryption, any sensitive data that is being sent between two computers or systems, preventing criminals from reading or modifying the information that is being transferred between the two parties.
In order to show that a website or app is protected by the SSL protocol, entities know as Certification Authorities issue SSL Certificates. Every time a browser initiates connection with an SSL secured website, it checks whether or not the certificate is up to date, whether it was issued by a trustworthy certification authority, and whether the certificate is being used by the website for which it was issued, and if all these are good, then the certificate is deemed valid and the connection secure. Secured websites will have HTTPS instead of HTTP in their URL.
There are three levels of SSL Certification: Extended Validation (EV), Organization Validated (OV), and Domain Validated (DV). They all provide encryption and data integrity, though they vary in terms of how much identity verification is involved and how the certificates display in browsers. EV SSL Certification is the highest form of SSL certification.
-What is Let’s Encrypt?
Let’s Encrypt is a nonprofit certification authority that provides SSL certification for free (usually there is a cost associated to acquiring SSL certification). Their certificates are valid for 90 days, but they have an automated process for the renewal of certificates for secure websites. Let’s Encrypt provides DV SSL Certification only.
